insert into departamentos values
(null,"Amazonas"),
(null,"Ancash"),
(null,"Apurímac"),
(null,"Arequipa"),
(null,"Ayacucho"),
(null,"Cajamarca"),
(null,"Cuzco"),
(null,"Huánuco"),
(null,"Ica"),
(null,"Junín"),
(null,"La Libertad"),
(null,"Lambayeque"),
(null,"Lima"),
(null,"Loreto"),
(null,"Madre de Dios"),
(null,"Moquegua"),
(null,"Pasco"),
(null,"Piura"),
(null,"Puno"),
(null,"San Martin"),
(null,"Tacna"),
(null,"Tumbes"),
(null,"Ucayali");

insert into sitios(nombre,id_departamento)
values
("Fortaleza de Kuélap",1),
("Sarcofagos de Karajía",1),
("La catarata de Gocta",1),
("Chavín de Huántar",2),
("Parque Nacional Huascarán",2),
("Callejón de Conchucos",2),
("Cordillera Blanca",2),
("Conjunto arqueológico de Saywite",3),
("Santuario Nacional de Ampay",3),
("Baños termales de Cconoc",3),
("Complejo arqueológico de Sondor",3),
("Plaza de Armas",4),
("Catedral de Arequipa",4),
("Yanahuara",4),
("Cañón del Colca",4),
("El Misti",4),
("Plaza de Armas",5),
("Sendero Luminoso",5),
("Catedral de Ayacucho",5),
("Celebraciones de Semana Santa",5),
("Plaza de Armas",6), 
("Iglesia Matriz Santa Catalina",6), 
("Conjunto monumental de Belén",6),
("Calle Hatunrumiyoc",7),
("La Montaña de los 7 Colores de Palcoyo",7),
("Laguna Humantay",7),
("Macchu Picchu",7);

